// frontend-sveltekit/src/routes/(admin)/admin/login/+page.svelte
<script lang="ts">
	import type { ActionData } from './$types';

	let { form }: { form: ActionData } = $props();
</script>

<svelte:head>
	<title>Admin Login | Moditimewatch</title>
</svelte:head>

<div class="login-container">
	<div class="login-card">
		<div class="login-header">
			<h1>Moditimewatch</h1>
			<p>Admin Panel</p>
		</div>

		{#if form?.error}
			<div class="error-message">
				{form.error}
			</div>
		{/if}

		<form method="POST" class="login-form">
			<div class="form-field">
				<label for="email">Email</label>
				<input
					type="email"
					id="email"
					name="email"
					value={form?.email ?? ''}
					placeholder="admin@example.com"
					required
					autocomplete="email"
				/>
			</div>

			<div class="form-field">
				<label for="password">Password</label>
				<input
					type="password"
					id="password"
					name="password"
					placeholder="••••••••"
					required
					autocomplete="current-password"
				/>
			</div>

			<button type="submit" class="login-button">Sign In</button>
		</form>

		<p class="login-footer">Manage products, orders, and content</p>
	</div>
</div>

<style>
	.login-container {
		min-height: 100vh;
		display: flex;
		align-items: center;
		justify-content: center;
		background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
		padding: 1rem;
	}

	.login-card {
		width: 100%;
		max-width: 400px;
		background: white;
		border-radius: 12px;
		padding: 2.5rem;
		box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
	}

	.login-header {
		text-align: center;
		margin-bottom: 2rem;
	}

	.login-header h1 {
		font-size: 1.75rem;
		font-weight: 700;
		color: #1a1a2e;
		margin: 0 0 0.5rem;
	}

	.login-header p {
		font-size: 0.875rem;
		color: #666;
		margin: 0;
	}

	.error-message {
		background: #fee2e2;
		color: #dc2626;
		padding: 0.75rem 1rem;
		border-radius: 8px;
		margin-bottom: 1.5rem;
		font-size: 0.875rem;
	}

	.login-form {
		display: flex;
		flex-direction: column;
		gap: 1.25rem;
	}

	.form-field {
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
	}

	.form-field label {
		font-size: 0.875rem;
		font-weight: 500;
		color: #374151;
	}

	.form-field input {
		padding: 0.75rem 1rem;
		border: 1px solid #d1d5db;
		border-radius: 8px;
		font-size: 1rem;
		transition: border-color 0.2s, box-shadow 0.2s;
	}

	.form-field input:focus {
		outline: none;
		border-color: #3b82f6;
		box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
	}

	.login-button {
		width: 100%;
		padding: 0.875rem 1rem;
		background: #1a1a2e;
		color: white;
		border: none;
		border-radius: 8px;
		font-size: 1rem;
		font-weight: 600;
		cursor: pointer;
		transition: background 0.2s;
		margin-top: 0.5rem;
	}

	.login-button:hover {
		background: #2d2d4a;
	}

	.login-footer {
		text-align: center;
		font-size: 0.75rem;
		color: #9ca3af;
		margin: 1.5rem 0 0;
	}
</style>

// backend-expressjs/components/Login.tsx
import React, { useState } from 'react';
import { Box, H2, Text, Input, Button, Label, MessageBox } from '@adminjs/design-system';

const Login = (props: any) => {
	const { action, errorMessage } = props;
	const [email, setEmail] = useState('');
	const [password, setPassword] = useState('');

	return (
		<Box
			bg="white"
			height="100vh"
			display="flex"
			alignItems="center"
			justifyContent="center"
			flexDirection="column"
		>
			<Box
				bg="grey20"
				borderRadius="lg"
				padding="xxl"
				width="400px"
				boxShadow="card"
			>
				<Box textAlign="center" mb="xxl">
					<H2 mb="default">SEO Campaign Manager</H2>
					<Text opacity={0.8}>
						Professional SEO content management platform for search engine optimization,
						programmatic SEO campaigns, and organic traffic growth.
					</Text>
				</Box>

				{errorMessage && (
					<MessageBox message={errorMessage} variant="danger" mb="xl" />
				)}

				<form action={action} method="POST">
					<Box mb="lg">
						<Label htmlFor="email">Email</Label>
						<Input
							id="email"
							name="email"
							type="email"
							value={email}
							onChange={(e: any) => setEmail(e.target.value)}
							placeholder="admin@example.com"
							required
						/>
					</Box>

					<Box mb="xl">
						<Label htmlFor="password">Password</Label>
						<Input
							id="password"
							name="password"
							type="password"
							value={password}
							onChange={(e: any) => setPassword(e.target.value)}
							placeholder="••••••••"
							required
						/>
					</Box>

					<Button variant="primary" size="lg" width="100%" type="submit">
						Sign In
					</Button>
				</form>

				<Box textAlign="center" mt="lg" opacity={0.6}>
					<Text variant="sm">Manage content, track rankings, grow traffic</Text>
				</Box>
			</Box>
		</Box>
	);
};

export default Login;
